use crate::pipeline::reproduce::GeneratedPoc;
use std::fs;
use std::path::Path;

/// Write generated PoCs to a directory.
/// Creates one script file per PoC plus a README index.
pub fn write_pocs(output_dir: &Path, protocol: &str, pocs: &[GeneratedPoc]) -> std::io::Result<()> {
    // Create output directory
    fs::create_dir_all(output_dir)?;

    // Write each PoC script, tracking safe names for README/index
    let mut written: Vec<(String, &GeneratedPoc)> = Vec::new(); // (safe_name, poc)
    let mut used_names = std::collections::HashSet::new();

    for (i, poc) in pocs.iter().enumerate() {
        // Sanitize the LLM-provided script_name to prevent path traversal
        let mut safe_name: String = poc
            .poc
            .script_name
            .replace(['/', '\\'], "")
            .replace("..", "")
            .chars()
            .filter(|c| c.is_alphanumeric() || *c == '_' || *c == '.' || *c == '-')
            .collect();

        // Fallback for empty or invalid names
        if safe_name.is_empty() || safe_name == "." || safe_name.starts_with('.') {
            safe_name = format!(
                "poc_{}_{}.py",
                i + 1,
                &poc.lead_fingerprint[..8.min(poc.lead_fingerprint.len())]
            );
        }

        // Handle duplicate names by appending index
        if used_names.contains(&safe_name) {
            let stem = safe_name.trim_end_matches(".py");
            safe_name = format!("{}_{}.py", stem, i + 1);
        }
        used_names.insert(safe_name.clone());

        let script_path = output_dir.join(&safe_name);

        // Prepend security warning to generated script
        let code_with_warning = format!(
            "# WARNING: This script is for authorized security testing only.\n\
             # Do not use against systems you do not own or have permission to test.\n\
             # Generated by RFC Analyzer from protocol specification analysis.\n\n{}",
            poc.poc.code
        );
        fs::write(&script_path, &code_with_warning)?;

        // Make executable on Unix
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&script_path)?.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&script_path, perms)?;
        }

        tracing::info!("Wrote {}", script_path.display());
        written.push((safe_name, poc));
    }

    // Write README index using actual safe filenames
    let readme = generate_readme_with_names(protocol, &written);
    fs::write(output_dir.join("README.md"), readme)?;

    // Write machine-readable index with actual filenames
    let index: Vec<serde_json::Value> = written
        .iter()
        .map(|(name, poc)| {
            serde_json::json!({
                "filename": name,
                "lead_fingerprint": poc.lead_fingerprint,
                "lead_technique": poc.lead_technique,
                "lead_severity": poc.lead_severity,
                "lead_category": poc.lead_category,
                "description": poc.poc.description,
                "setup": poc.poc.setup,
                "expected_vulnerable": poc.poc.expected_vulnerable,
                "expected_patched": poc.poc.expected_patched,
                "caveats": poc.poc.caveats,
            })
        })
        .collect();
    let index_json = serde_json::to_string_pretty(&index).unwrap_or_else(|_| "[]".to_string());
    fs::write(output_dir.join("index.json"), index_json)?;

    tracing::info!(
        "Wrote {} PoCs + README to {}",
        pocs.len(),
        output_dir.display()
    );

    Ok(())
}

/// Generate a README.md index using actual written filenames.
fn generate_readme_with_names(protocol: &str, written: &[(String, &GeneratedPoc)]) -> String {
    let mut readme = format!(
        "# {} Protocol — Proof-of-Concept Scripts\n\n\
         Generated by RFC Analyzer from protocol specification analysis.\n\n\
         **WARNING**: These scripts are for authorized security testing only.\n\
         Do not use against systems you do not own or have permission to test.\n\n\
         ## Scripts\n\n\
         | # | Script | Severity | Category | Technique |\n\
         |---|--------|----------|----------|-----------|\n",
        protocol.to_uppercase()
    );

    for (i, (name, poc)) in written.iter().enumerate() {
        readme.push_str(&format!(
            "| {} | [{}]({}) | {} | {} | {} |\n",
            i + 1,
            name,
            name,
            poc.lead_severity,
            poc.lead_category,
            poc.lead_technique
        ));
    }

    readme.push_str("\n## Details\n\n");

    for (_, poc) in written {
        readme.push_str(&format!("### {}\n\n", poc.lead_technique));
        readme.push_str(&format!(
            "**Severity**: {} | **Category**: {}\n\n",
            poc.lead_severity, poc.lead_category
        ));
        readme.push_str(&format!("{}\n\n", poc.poc.description));

        readme.push_str("**Setup**:\n");
        for step in &poc.poc.setup {
            readme.push_str(&format!("1. {}\n", step));
        }

        readme.push_str(&format!(
            "\n**If vulnerable**: {}\n\n",
            poc.poc.expected_vulnerable
        ));
        readme.push_str(&format!("**If patched**: {}\n\n", poc.poc.expected_patched));

        if !poc.poc.caveats.is_empty() {
            readme.push_str("**Caveats**:\n");
            for caveat in &poc.poc.caveats {
                readme.push_str(&format!("- {}\n", caveat));
            }
        }
        readme.push_str("\n---\n\n");
    }

    readme
}

/// Generate a README.md index for the PoC directory (legacy, uses original names).
pub fn generate_readme(protocol: &str, pocs: &[GeneratedPoc]) -> String {
    let mut readme = format!(
        "# {} Protocol — Proof-of-Concept Scripts\n\n\
         Generated by RFC Analyzer from protocol specification analysis.\n\n\
         **WARNING**: These scripts are for authorized security testing only.\n\
         Do not use against systems you do not own or have permission to test.\n\n\
         ## Scripts\n\n\
         | # | Script | Severity | Category | Technique |\n\
         |---|--------|----------|----------|-----------|\n",
        protocol.to_uppercase()
    );

    for (i, poc) in pocs.iter().enumerate() {
        readme.push_str(&format!(
            "| {} | [{}]({}) | {} | {} | {} |\n",
            i + 1,
            poc.poc.script_name,
            poc.poc.script_name,
            poc.lead_severity,
            poc.lead_category,
            poc.lead_technique
        ));
    }

    readme.push_str("\n## Details\n\n");

    for poc in pocs {
        readme.push_str(&format!("### {}\n\n", poc.lead_technique));
        readme.push_str(&format!(
            "**Severity**: {} | **Category**: {}\n\n",
            poc.lead_severity, poc.lead_category
        ));
        readme.push_str(&format!("{}\n\n", poc.poc.description));

        readme.push_str("**Setup**:\n");
        for step in &poc.poc.setup {
            readme.push_str(&format!("1. {}\n", step));
        }

        readme.push_str(&format!(
            "\n**If vulnerable**: {}\n\n",
            poc.poc.expected_vulnerable
        ));
        readme.push_str(&format!("**If patched**: {}\n\n", poc.poc.expected_patched));

        if !poc.poc.caveats.is_empty() {
            readme.push_str("**Caveats**:\n");
            for caveat in &poc.poc.caveats {
                readme.push_str(&format!("- {}\n", caveat));
            }
        }
        readme.push_str("\n---\n\n");
    }

    readme
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pipeline::reproduce::PocResponse;

    #[test]
    fn test_generate_readme() {
        let pocs = vec![GeneratedPoc {
            lead_fingerprint: "abc".to_string(),
            lead_technique: "SLC Overflow".to_string(),
            lead_severity: "high".to_string(),
            lead_category: "OversizedPayload".to_string(),
            poc: PocResponse {
                script_name: "poc_slc.py".to_string(),
                description: "Sends oversized SLC triplets".to_string(),
                setup: vec!["Start telnetd".to_string()],
                code: "print('test')".to_string(),
                expected_vulnerable: "Crash".to_string(),
                expected_patched: "Rejected".to_string(),
                caveats: vec!["Requires network access".to_string()],
            },
        }];

        let readme = generate_readme("telnet", &pocs);
        assert!(readme.contains("TELNET"));
        assert!(readme.contains("poc_slc.py"));
        assert!(readme.contains("SLC Overflow"));
        assert!(readme.contains("WARNING"));
    }

    #[test]
    fn test_generate_readme_empty() {
        let readme = generate_readme("test", &[]);
        assert!(readme.contains("TEST"));
        assert!(!readme.contains("| 1 |")); // No entries table row
    }

    #[test]
    fn test_write_pocs_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let pocs = vec![GeneratedPoc {
            lead_fingerprint: "fp1".to_string(),
            lead_technique: "Test".to_string(),
            lead_severity: "high".to_string(),
            lead_category: "MissingValidation".to_string(),
            poc: PocResponse {
                script_name: "poc_test.py".to_string(),
                description: "Test".to_string(),
                setup: vec![],
                code: "#!/usr/bin/env python3\nprint('test')".to_string(),
                expected_vulnerable: "Crash".to_string(),
                expected_patched: "OK".to_string(),
                caveats: vec![],
            },
        }];

        write_pocs(dir.path(), "test", &pocs).unwrap();

        assert!(dir.path().join("poc_test.py").exists());
        assert!(dir.path().join("README.md").exists());
        assert!(dir.path().join("index.json").exists());

        let script = std::fs::read_to_string(dir.path().join("poc_test.py")).unwrap();
        assert!(script.contains("# WARNING:"));
        assert!(script.contains("print('test')"));
    }

    #[test]
    fn test_write_pocs_sanitizes_script_name() {
        let dir = tempfile::tempdir().unwrap();
        let pocs = vec![GeneratedPoc {
            lead_fingerprint: "fp1".to_string(),
            lead_technique: "Test".to_string(),
            lead_severity: "high".to_string(),
            lead_category: "MissingValidation".to_string(),
            poc: PocResponse {
                script_name: "../../../etc/evil.py".to_string(),
                description: "Path traversal attempt".to_string(),
                setup: vec![],
                code: "#!/usr/bin/env python3\nprint('evil')".to_string(),
                expected_vulnerable: "Crash".to_string(),
                expected_patched: "OK".to_string(),
                caveats: vec![],
            },
        }];

        write_pocs(dir.path(), "test", &pocs).unwrap();

        // Should be sanitized to just the filename without path components
        let files: Vec<_> = std::fs::read_dir(dir.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect();
        assert!(!files.iter().any(|f| f.contains("..")));
    }

    #[test]
    fn test_write_pocs_multiple() {
        let dir = tempfile::tempdir().unwrap();
        let pocs = vec![
            GeneratedPoc {
                lead_fingerprint: "fp1".to_string(),
                lead_technique: "Attack A".to_string(),
                lead_severity: "critical".to_string(),
                lead_category: "X".to_string(),
                poc: PocResponse {
                    script_name: "poc_a.py".to_string(),
                    description: "A".to_string(),
                    setup: vec![],
                    code: "# a".to_string(),
                    expected_vulnerable: "Crash".to_string(),
                    expected_patched: "OK".to_string(),
                    caveats: vec![],
                },
            },
            GeneratedPoc {
                lead_fingerprint: "fp2".to_string(),
                lead_technique: "Attack B".to_string(),
                lead_severity: "high".to_string(),
                lead_category: "Y".to_string(),
                poc: PocResponse {
                    script_name: "poc_b.py".to_string(),
                    description: "B".to_string(),
                    setup: vec![],
                    code: "# b".to_string(),
                    expected_vulnerable: "Leak".to_string(),
                    expected_patched: "OK".to_string(),
                    caveats: vec!["Limitation 1".to_string()],
                },
            },
        ];

        write_pocs(dir.path(), "test", &pocs).unwrap();

        assert!(dir.path().join("poc_a.py").exists());
        assert!(dir.path().join("poc_b.py").exists());
        assert!(dir.path().join("README.md").exists());
        assert!(dir.path().join("index.json").exists());

        let readme = std::fs::read_to_string(dir.path().join("README.md")).unwrap();
        assert!(readme.contains("Attack A"));
        assert!(readme.contains("Attack B"));
        assert!(readme.contains("Limitation 1"));

        let index_content = std::fs::read_to_string(dir.path().join("index.json")).unwrap();
        assert!(index_content.contains("fp1"));
        assert!(index_content.contains("fp2"));
    }
}
